//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int id_produto { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public string url { get; set; }
    }
}
